// Catálogo de vagas de /empregos — extraído de app/empregos/page.tsx em
// 25/set/2026 pra poder ser importado tanto pela página (client) quanto
// pela nova API de candidatura (server, app/api/empregos-candidatura/
// route.ts), que precisa consultar setor/idioma/perfil da vaga pra pontuar
// o currículo do candidato. Mesmo padrão de extração já usado em
// app/lib/calculadoraCatalogoPublico.ts (separar dado puro de componente
// "use client" — API routes não podem importar de um módulo "use
// client"). Nenhum dado foi alterado, é uma cópia exata do que já estava
// em page.tsx.

export type PublicoKey = "brasil" | "japao";

export type SetorKey = "automotivo" | "eletronicos" | "alimenticio" | "materiais";

export type StatusVaga = "aberta" | "consulta";

export type Vaga = {
  id: string;
  empresa: string;
  titulo: string;
  setor: SetorKey;
  regiao: string;
  cidade: string;
  publico: PublicoKey[];
  turno: string;
  contrato: string;
  salario: string;
  status: StatusVaga;
  idioma?: string;
  perfil?: string;
  logo?: string;
  conducao?: string;
  observacoes?: string;
  fonteContrato?: "ut-suriemu";
};

export const VAGAS: Vaga[] = [
  // ── Avance RH/Corporation — comunicado + fichas individuais ──
  {
    id: "fuji-seat-higashiomi",
    empresa: "Fuji Seat",
    titulo: "Montagem e inspeção de bancos de carro",
    setor: "automotivo",
    regiao: "Shiga",
    cidade: "Higashiomi",
    publico: ["brasil"],
    turno: "Turno alternado semanalmente (diurno/noturno), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.400/hora",
    status: "aberta",
    idioma: "Não mandatório",
    perfil: "Homens até 45 anos",
  },
  {
    id: "aisin-shinwa-toyama",
    empresa: "Aisin Shinwa",
    titulo: "Processamento e inspeção de autopeças",
    setor: "automotivo",
    regiao: "Toyama",
    cidade: "Shimoniikawa Gun",
    publico: ["brasil"],
    turno: "Turno alternado semanalmente, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.600/hora",
    status: "aberta",
    logo: "/images/logo-cliente-aisin.png",
    idioma: "Básico (N4), preferência razoável (N3)",
    perfil: "Homens até 45 anos — precisa ter carro próprio e experiência em fábrica no Brasil ou no Japão",
  },
  {
    id: "marugo-gomu-okayama",
    empresa: "Marugo Gomu",
    titulo: "Vulcanização, acabamento e inspeção de mangueiras automotivas",
    setor: "automotivo",
    regiao: "Okayama",
    cidade: "Oda Yakage-cho",
    publico: ["brasil"],
    turno: "Turno alternado semanalmente, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.250–1.530/hora, conforme a função",
    status: "aberta",
    idioma: "Não mandatório",
    perfil: "Homens e mulheres até 50 anos",
  },
  {
    id: "murata-izumo",
    empresa: "Murata",
    titulo: "Produção de componentes eletrônicos (condensador cerâmico)",
    setor: "eletronicos",
    regiao: "Shimane",
    cidade: "Izumo",
    publico: ["brasil"],
    turno: "Turno fixo, diurno ou noturno, 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.340–1.390/hora (até ¥1.560/hora conforme desempenho)",
    status: "aberta",
    logo: "/images/logo-cliente-murata.png",
    idioma: "Não mandatório",
    perfil: "Homem, mulher ou casal até 50 anos",
  },
  {
    id: "murata-oda",
    empresa: "Murata",
    titulo: "Produção de componentes eletrônicos (condensador cerâmico)",
    setor: "eletronicos",
    regiao: "Shimane",
    cidade: "Oda",
    publico: ["brasil"],
    turno: "Turno fixo, diurno ou noturno, 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.340/hora (até ¥1.560/hora conforme desempenho)",
    status: "aberta",
    logo: "/images/logo-cliente-murata.png",
    idioma: "Não mandatório",
    perfil: "Homem, mulher ou casal até 50 anos",
  },
  {
    id: "daikin-kusatsu",
    empresa: "Daikin",
    titulo: "Produção, montagem e inspeção de ar-condicionado",
    setor: "eletronicos",
    regiao: "Shiga",
    cidade: "Kusatsu",
    publico: ["brasil"],
    turno: "Turno alternado semanalmente (diurno/noturno), 5x2 ou 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.400/hora (até ¥1.650/hora conforme desempenho)",
    status: "consulta",
    logo: "/images/logo-cliente-daikin.png",
    idioma: "Básico (N4)",
    perfil: "Homens e mulheres até 45 anos — previsão de vagas a partir de outubro/novembro",
  },
  {
    id: "cs-nakatsugawa-gifu",
    empresa: "CS Nakatsugawa",
    titulo: "Produção e inspeção de sensores automotivos",
    setor: "automotivo",
    regiao: "Gifu",
    cidade: "Nakatsugawa",
    publico: ["brasil"],
    turno: "Turno fixo ou alternado, 5x2 ou 6x1",
    contrato: "Haken ou ukeoi, conforme a vaga",
    salario: "¥1.400/hora",
    status: "consulta",
    idioma: "Preferencialmente com conhecimento de japonês",
    perfil: "Homens até 55 anos, não fumante",
  },
  {
    id: "ntk-kani-gifu",
    empresa: "NTK Kani",
    titulo: "Operação de máquina e inspeção de velas automotivas",
    setor: "automotivo",
    regiao: "Gifu",
    cidade: "Kani",
    publico: ["brasil"],
    turno: "Turno alternado mensalmente, 5x2 ou 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.300–1.400/hora, conforme o setor",
    status: "consulta",
    idioma: "Zero ou razoável (N3), a depender do setor",
    perfil: "Homem, mulher ou casal até 45 anos",
  },
  {
    id: "nitto-boseki-fukushima",
    empresa: "Nitto Boseki",
    titulo: "Produção de peças de fibra de vidro",
    setor: "materiais",
    regiao: "Fukushima",
    cidade: "Fukushima",
    publico: ["brasil"],
    turno: "3 turnos (05:55–14:15 / 13:55–22:15 / 21:55–06:15)",
    contrato: "Terceirizado (Out-Sourcing)",
    salario: "¥1.300/hora",
    status: "consulta",
    idioma: "Básico (N4)",
    perfil: "Homens até 50 anos — previsão de vagas a partir de setembro",
  },
  // ── UT Suri-emu — fichas de contrato por empresa ──
  {
    id: "subaru-oizumi",
    empresa: "Subaru",
    titulo: "Montagem, abastecimento e inspeção de veículos",
    setor: "automotivo",
    regiao: "Gunma",
    cidade: "Oizumi",
    publico: ["brasil"],
    turno: "Turno alternado (diurno/noturno/sankoutai, conforme escala)",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.800–1.900/hora",
    status: "aberta",
    logo: "/images/logo-cliente-subaru.png",
    conducao: "Bicicleta (alugada pela empresa) — condução própria (carro/moto) possível, consultar a unidade.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "subaru-ota",
    empresa: "Subaru",
    titulo: "Montagem, abastecimento e inspeção de veículos",
    setor: "automotivo",
    regiao: "Gunma",
    cidade: "Ota",
    publico: ["brasil"],
    turno: "Turno alternado (diurno/noturno), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.800–1.900/hora",
    status: "aberta",
    logo: "/images/logo-cliente-subaru.png",
    conducao: "Bicicleta (alugada pela empresa) — condução própria (carro/moto) possível, consultar a unidade.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "mitsubishi-fuso-toyama",
    empresa: "Mitsubishi Fuso",
    titulo: "Produção de ônibus — inspeção, soldagem, pintura e montagem",
    setor: "automotivo",
    regiao: "Toyama",
    cidade: "Toyama",
    publico: ["brasil"],
    turno: "Turno fixo ou alternado (diurno/noturno), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.700/hora",
    status: "aberta",
    conducao: "Vans/ônibus (gratuito), bicicleta (alugada pela empresa) ou a pé — condução própria (carro/moto) possível, consultar a unidade.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "yamase-miyagi",
    empresa: "Yamase Electronics",
    titulo: "Montagem e inspeção de peças eletrônicas automotivas",
    setor: "automotivo",
    regiao: "Miyagi",
    cidade: "Osaki",
    publico: ["brasil"],
    turno: "Turno fixo, diurno ou noturno, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.200/hora (até ¥1.250/hora após o 3º mês)",
    status: "aberta",
  },
  {
    id: "fujifilm-miyagi",
    empresa: "Fuji Film",
    titulo: "Montagem e inspeção de lentes de câmeras digitais",
    setor: "eletronicos",
    regiao: "Miyagi",
    cidade: "Taiwa",
    publico: ["brasil"],
    turno: "Diurno fixo, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.200–1.250/hora",
    status: "aberta",
    logo: "/images/logo-cliente-fujifilm.png",
  },
  {
    id: "yokohama-gomu-aichi",
    empresa: "Yokohama Gomu",
    titulo: "Montagem de borracha e inspeção de pneus",
    setor: "automotivo",
    regiao: "Aichi",
    cidade: "Shinshiro",
    publico: ["brasil"],
    turno: "Turno alternado (diurno/noturno), 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.430/hora",
    status: "aberta",
    logo: "/images/logo-cliente-yokohama-tyres.png",
    conducao: "Vans/ônibus (gratuito), bicicleta (alugada pela empresa) ou a pé — condução própria (carro/moto) possível, consultar a unidade.",
    observacoes: "Uniforme cobrado à parte, ¥6.450.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "sony-aichi",
    empresa: "Sony",
    titulo: "Montagem e inspeção de filmadoras e lentes digitais",
    setor: "eletronicos",
    regiao: "Aichi",
    cidade: "Kohda",
    publico: ["brasil"],
    turno: "Diurno ou noturno fixo, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.100/hora",
    status: "aberta",
    logo: "/images/logo-cliente-sony.png",
  },
  {
    id: "mitsubishi-denki-himeji",
    empresa: "Mitsubishi Denki",
    titulo: "Produção de alternadores automotivos",
    setor: "automotivo",
    regiao: "Hyogo",
    cidade: "Himeji",
    publico: ["brasil"],
    turno: "Diurno fixo (8:30–17:00), noturno fixo (20:45–5:30) ou alternado, 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.300/hora (extra ¥1.625/hora; noturno +¥325/hora)",
    status: "aberta",
    logo: "/images/logo-cliente-mitsubishi-denki.png",
  },
  {
    id: "daihatsu-nakatsu",
    empresa: "Daihatsu",
    titulo: "Montagem e inspeção de automóveis",
    setor: "automotivo",
    regiao: "Oita",
    cidade: "Nakatsu",
    publico: ["brasil"],
    turno: "Turno alternado (diurno 6:30–15:10 / vespertino 18:30–2:40), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.800/hora (extra ¥2.250/hora; noturno +¥450/hora) + bônus de permanência de até ¥500.000 no primeiro ano e meio",
    status: "aberta",
    idioma: "Básico",
    perfil: "18 a 39 anos (até 45 com experiência) — avaliação médica e física admissional",
  },
  {
    id: "fruehauf-atsugi",
    empresa: "Fruehauf",
    titulo: "Montagem e pintura de carrocerias de caminhão",
    setor: "automotivo",
    regiao: "Kanagawa",
    cidade: "Atsugi",
    publico: ["brasil"],
    turno: "Diurno fixo (8:05–17:00), 5x2 — sem turno noturno",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.600/hora (extra ¥2.000/hora; noturno +¥400/hora)",
    status: "aberta",
    idioma: "Básico (identificar avisos e placas de segurança)",
    perfil: "Homens até 50 anos (acima de 45 com experiência) — vagas femininas em negociação; requer visita à fábrica antes da alocação",
    conducao: "Bicicleta (alugada pela empresa) ou a pé — condução própria (carro/moto) possível, consultar a unidade.",
    observacoes: "Estacionamento por conta do funcionário, ¥2.200/mês.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "gs-yuasa-ritto",
    empresa: "GS Yuasa",
    titulo: "Produção de baterias para veículos elétricos e híbridos",
    setor: "automotivo",
    regiao: "Shiga",
    cidade: "Ritto",
    publico: ["brasil"],
    turno: "Turno alternado (diurno 9:00–21:00 / noturno 21:00–9:00), 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.400/hora, com reajuste semestral por assiduidade até ¥1.500/hora",
    status: "aberta",
  },
  // ── Fujiarte Co. Ltd. — fichas "Condições de Contrato" (Inoac e Futaba
  // Sangyou, propostas atualizadas de 1/abr/2026) ──
  {
    id: "inoac-sakurai",
    empresa: "Inoac Corporation",
    titulo: "Produção de peças de aerofólio automotivo",
    setor: "automotivo",
    regiao: "Aichi",
    cidade: "Anjo",
    publico: ["brasil"],
    turno: "Turno alternado (7:00–16:00 / 19:00–4:00), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.300/hora (após 3 meses, ¥1.400/hora) + moradia ¥55.000–60.000",
    status: "aberta",
    perfil: "Homens solteiros ou casais — para casal com filho menor de idade, a vaga é garantida só para o marido, sem suporte de passagem para a família",
  },
  {
    id: "inoac-kira",
    empresa: "Inoac Corporation",
    titulo: "Fabricação de encosto de cabeça e apoio de copos automotivo",
    setor: "automotivo",
    regiao: "Aichi",
    cidade: "Kira",
    publico: ["brasil"],
    turno: "Turno alternado (7:00–16:00 / 18:00–3:00), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.300/hora (após 3 meses, ¥1.400/hora) + moradia ¥45.000–65.000",
    status: "aberta",
    perfil: "Homens solteiros ou casais — para casal com filho menor de idade, a vaga é garantida só para o marido, sem suporte de passagem para a família",
  },
  {
    id: "futaba-mutsumi",
    empresa: "Futaba Sangyou",
    titulo: "Fabricação de peças de chassi automotivo",
    setor: "automotivo",
    regiao: "Aichi",
    cidade: "Okazaki",
    publico: ["brasil"],
    turno: "Turno alternado (8:00–16:45 / 20:00–4:45), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.550/hora (após 6 meses, ¥1.650/hora) + moradia ¥45.000–60.000",
    status: "aberta",
    perfil: "Homens solteiros ou casais com filhos — para casal com filho menor de idade, a vaga é garantida só para o marido, sem suporte de passagem para a família. Alocação entre Kota, Mutsumi e Okazaki definida só após a chegada ao Japão",
  },
  {
    id: "futaba-kota",
    empresa: "Futaba Sangyou",
    titulo: "Fabricação de escapamento automotivo",
    setor: "automotivo",
    regiao: "Aichi",
    cidade: "Kota",
    publico: ["brasil"],
    turno: "Turno alternado (8:00–16:45 / 20:00–4:45), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.550/hora (após 6 meses, ¥1.650/hora) + moradia ¥45.000–60.000",
    status: "aberta",
    perfil: "Homens solteiros ou casais com filhos — para casal com filho menor de idade, a vaga é garantida só para o marido, sem suporte de passagem para a família",
  },
  {
    id: "fujifilm-kanagawa",
    empresa: "Fuji Film",
    titulo: "Embalamento de filmes instantâneos para câmeras fotográficas",
    setor: "eletronicos",
    regiao: "Kanagawa",
    cidade: "Minami Ashigara",
    publico: ["brasil"],
    turno: "Diurno fixo (7:00–16:00) ou noturno fixo (19:00–4:00), 5x2 ou 4x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.350/hora (extra ¥1.688/hora; noturno +¥338/hora)",
    status: "aberta",
    logo: "/images/logo-cliente-fujifilm.png",
    conducao: "Bicicleta (alugada pela empresa) ou a pé — condução própria de carro possível, consultar a unidade.",
    observacoes: "Apartamentos Leopalace geralmente já incluem TV, cortina, mesa, ar-condicionado, máquina de lavar, geladeira e micro-ondas.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "hino-jidousha-ota",
    empresa: "Hino Jidosha",
    titulo: "Montagem e usinagem de peças de motor de caminhão",
    setor: "automotivo",
    regiao: "Gunma",
    cidade: "Ota",
    publico: ["brasil"],
    turno: "Turno alternado (diurno 6:30–15:20 / noturno 17:15–2:05), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥2.000/hora (extra ¥2.500/hora; noturno +¥500/hora)",
    status: "aberta",
    conducao: "A pé — bicicleta própria possível, consultar a unidade.",
    observacoes: "Refeitório na unidade com geladeira e micro-ondas.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "hino-jidousha-hamura",
    empresa: "Hino Jidosha",
    titulo: "Montagem, abastecimento e inspeção de veículos",
    setor: "automotivo",
    regiao: "Tokyo",
    cidade: "Hamura",
    publico: ["brasil"],
    turno: "Turno alternado (diurno 6:30–15:20 / noturno 17:15–2:05), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥2.000/hora (extra ¥2.500/hora; noturno +¥500/hora)",
    status: "aberta",
    conducao: "A pé — bicicleta própria possível, consultar a unidade.",
    observacoes: "Refeitório com sistema de recarga (depósito-caução de ¥1.000); cada refeição custa em torno de ¥500.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "kitz-ina-nagano",
    empresa: "Kitz",
    titulo: "Produção de válvulas de água — montagem, usinagem e inspeção",
    setor: "materiais",
    regiao: "Nagano",
    cidade: "Ina",
    publico: ["brasil"],
    turno: "Diurno fixo (8:25–17:25) ou alternado (hayaban 5:00–13:20 / osoban 13:15–21:35), 5x2",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.200/hora (mulheres) ou ¥1.300/hora (homens)",
    status: "aberta",
    conducao: "Vans/ônibus (gratuito), bicicleta (alugada pela empresa) ou a pé.",
    fonteContrato: "ut-suriemu",
  },
  {
    id: "panasonic-gunma",
    empresa: "Panasonic",
    titulo: "Produção de eletrodomésticos — tratamento térmico, máquina e montagem",
    setor: "eletronicos",
    regiao: "Gunma",
    cidade: "Oizumi",
    publico: ["brasil"],
    turno: "Diurno fixo (8:25–17:00), 5x2 — possibilidade de turno noturno conforme a necessidade",
    contrato: "Contrato temporário (haken)",
    salario: "¥1.300–1.500/hora, conforme japonês e habilidades (até ¥1.600/hora em lift, até ¥1.900/hora em solda)",
    status: "aberta",
    logo: "/images/logo-cliente-panasonic.png",
    conducao: "Bicicleta (alugada pela empresa) ou a pé — condução própria (carro/moto) possível, consultar a unidade.",
    fonteContrato: "ut-suriemu",
  },
];

export function encontrarVaga(id: string): Vaga | null {
  return VAGAS.find((v) => v.id === id) ?? null;
}
